# Gradle
org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configureondemand=true

# Kotlin
kotlin.code.style=official

# Publishing
REPOSITORY_URL=https://github.com/boris4110799/ComposingBuildLogic
GITHUB_MAVEN_URL=https://maven.pkg.github.com/boris4110799/ComposingBuildLogic
